export const types = {
    SET_LIGHT_THEME: 'SET_LIGHT_THEME',
    SET_DARK_THEME: 'SET_DARK_THEME',
    SET_HAS_ACTION: 'SET_HAS_ACTION',
    SET_HAS_CLICKED_ACTION: 'SET_HAS_CLICKED_ACTION',
    SET_NOTIFICATIONS: 'SET_NOTIFICATIONS'
};