export const types = {
    CREATE_USER: "CREATE_USER",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    ME: "ME",
    LOGOUT: "LOGOUT",
    UPDATE_PROFILE_PICTURE: "UPDATE_PROFILE_PICTURE",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER"
};
