export const types = {
    FETCH_RESOURCES: 'FETCH_RESOURCES',
    FETCH_RESOURCE: 'FETCH_RESOURCE',
    DELETE_RESOURCE: 'DELETE_RESOURCE',
    UPDATE_RESOURCE: 'UPDATE_RESOURCE',
    CREATE_RESOURCE: 'CREATE_RESOURCE',
};