export const types = {
    FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
    FETCH_NOTIFICATION: 'FETCH_NOTIFICATION',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
    UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
    CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
    COUNT_NOTIFICATIONS: 'COUNT_NOTIFICATIONS'
};