export const types = {
    FETCH_TRANSACTION_PARTNERS: 'FETCH_TRANSACTION_PARTNERS',
    FETCH_TRANSACTION_PARTNER: 'FETCH_TRANSACTION_PARTNER',
    DELETE_TRANSACTION_PARTNER: 'DELETE_TRANSACTION_PARTNER',
    CREATE_TRANSACTION_PARTNER: 'CREATE_TRANSACTION_PARTNER',
    UPDATE_TRANSACTION_PARTNER: 'UPDATE_TRANSACTION_PARTNER',
    LIQUIDATE_TRANSACTION_PARTNER: 'LIQUIDATE_TRANSACTION_PARTNER',
};