export const types = {
    FETCH_CALENDARS: 'FETCH_CALENDARS',
    FETCH_CALENDAR: 'FETCH_CALENDAR',
    DELETE_CALENDAR: 'DELETE_CALENDAR',
    UPDATE_CALENDAR: 'UPDATE_CALENDAR',
    CREATE_CALENDAR: 'CREATE_CALENDAR',
    UPDATE_SELF_CALENDAR: 'UPDATE_SELF_CALENDAR'
};