export const types = {
    FETCH_NETWORKINGS: 'FETCH_NETWORKINGS',
    FETCH_NETWORKING: 'FETCH_NETWORKING',
    DELETE_NETWORKING: 'DELETE_NETWORKING',
    UPDATE_NETWORKING: 'UPDATE_NETWORKING',
    CREATE_NETWORKING: 'CREATE_NETWORKING',
};