export const types = {
    FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
    FETCH_TRANSACTION: 'FETCH_TRANSACTION',
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
    CREATE_TRANSACTION: 'CREATE_TRANSACTION',
};