export const types = {
    FETCH_TRANSACTION_CATEGORIES: 'FETCH_TRANSACTION_CATEGORIES',
    FETCH_TRANSACTION_CATEGORY: 'FETCH_TRANSACTION_CATEGORY',
    DELETE_TRANSACTION_CATEGORY: 'DELETE_TRANSACTION_CATEGORY',
    UPDATE_TRANSACTION_CATEGORY: 'UPDATE_TRANSACTION_CATEGORY',
    CREATE_TRANSACTION_CATEGORY: 'CREATE_TRANSACTION_CATEGORY',
};