export const types = {
    FETCH_PROGRAM_SESSIONS: 'FETCH_PROGRAM_SESSIONS',
    FETCH_PROGRAM_SESSION: 'FETCH_PROGRAM_SESSION',
    DELETE_PROGRAM_SESSION: 'DELETE_PROGRAM_SESSION',
    UPDATE_PROGRAM_SESSION: 'UPDATE_PROGRAM_SESSION',
    CREATE_PROGRAM_SESSION: 'CREATE_PROGRAM_SESSION',
};