export const types = {
    FETCH_TRACKERS: 'FETCH_TRACKERS',
    FETCH_TRACKER: 'FETCH_TRACKER',
    DELETE_TRACKER: 'DELETE_TRACKER',
    UPDATE_TRACKER: 'UPDATE_TRACKER',
    CREATE_TRACKER: 'CREATE_TRACKER',
};