export const types = {
    FETCH_SPONSORS: 'FETCH_SPONSORS',
    FETCH_SPONSOR: 'FETCH_SPONSOR',
    DELETE_SPONSOR: 'DELETE_SPONSOR',
    UPDATE_SPONSOR: 'UPDATE_SPONSOR',
    CREATE_SPONSOR: 'CREATE_SPONSOR',
};