export const types = {
    FETCH_QUESTIONS: 'FETCH_QUESTIONS',
    FETCH_QUESTION: 'FETCH_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION',
    UPDATE_QUESTION: 'UPDATE_QUESTION',
    CREATE_QUESTION: 'CREATE_QUESTION',
};