export const types = {
    FETCH_SPEAKERS: 'FETCH_SPEAKERS',
    FETCH_SPEAKER: 'FETCH_SPEAKER',
    DELETE_SPEAKER: 'DELETE_SPEAKER',
    UPDATE_SPEAKER: 'UPDATE_SPEAKER',
    CREATE_SPEAKER: 'CREATE_SPEAKER',
};